### ISSUE TITLE
question: repetitive create invite link error message mistake.

### ISSUE THREAD

**Issue by Jinchenyuan** [apitable/apitable#1050]
## When done creating the invitation link, click the Create button again to indicate that the content is wrong.

https://github.com/apitable/apitable/assets/10692218/9351a546-4ab2-44cf-bc3f-e30a37cf17f6

**Comment by nagisakon** [comment]
You have successfully created an invitation link, click to copy it and use it
![image](https://github.com/apitable/apitable/assets/49678762/e5c9fb66-30ed-42d5-9cf6-2e01e373c42e)

**Comment by mr-kelly** [comment]
I think this is a defect of UI experience. We will figure out how to improve it later

**Comment by mr-kelly** [comment]
Thank you for the report. Local compilation errors during `yarn dev` can stem from outdated dependencies, incorrect Node.js versions, or missing build steps (like `make install`). Since we haven't received further updates or full text logs to diagnose this specific environment issue, we will close it for now. Feel free to reopen it if the issue persists on the latest code.

---

感谢您的报告。在 `yarn dev` 期间的本地编译错误可能源于过时的依赖项、错误的 Node.js 版本或缺失的构建步骤（如 `make install`）。由于我们尚未收到进一步的更新或全文日志来诊断这个特定的环境问题，我们将暂时关闭它。如果在最新代码中问题仍然存在，请随时重新打开它。
