### ISSUE TITLE
有离线部署方案嘛？

### ISSUE THREAD

**Issue by forxiucn** [apitable/apitable#1055]
**描述Bug**
想在内网进行离线部署

**重现步骤**
尝试过通过把docker compose所包含的镜像导出，奈何依赖的东西太多，最终还是以失败告终。

**期望行为**
期望可以有一个离线部署方案，目前在官方站点所提供的文档支持上面暂未发现有相关信息。

**屏幕截图**
暂无

**电脑版（请填写以下信息）：**
暂无

**智能手机（请填写以下信息）：**
暂无

**其他上下文**
暂无

**Comment by mr-kelly** [comment]
Contact sales@apitable.com or fill [the form](https://apitable.com/share/shrdaGGppsfg3pjQLXALG) for the enterprise offline deployment solution.

**Comment by mr-kelly** [comment]
Since the issue only provides a general statement without specific container logs, it is difficult to determine the exact cause of the OpenResty failure. Typically, this happens when port 80/443 is already in use by another service on your machine, or when the Nginx configuration fails to mount. We will close this issue for now. Please feel free to reopen it with the output of `docker logs apitable-openresty-1`.

---

由于此 Issue 仅提供了一般性描述而没有具体的容器日志，因此很难确定 OpenResty 失败的确切原因。通常，当您机器上的另一个服务已经占用了 80/443 端口，或者 Nginx 配置未能成功挂载时，就会发生这种情况。我们将暂时关闭此 Issue。请随时提供 `docker logs apitable-openresty-1` 的输出并重新打开它。
