### ISSUE TITLE
question: AGPL License & Embedding 

### ISSUE THREAD

**Issue by ssddanbrown** [apitable/apitable#226]
Hello 👋,

Just came across this project and I was intrigued by the license text, specifically [the following](https://github.com/apitable/apitable/blob/e31924c1413833910c6359cad1e2c1fd08978d01/LICENSING.md?plain=1#L7-L9):

> ##### [GNU Affero General Public License](./LICENSE) (AGPL)
> If you remove the “Powered by APITable” logo on embedded APITable page, you’d then need to release your own embedding application under the AGPL. To avoid this, you can instead purchase an Enterprise Edition package.

Just to be up-front, I am not a lawyer but have spent some time attempting to understand the AGPLv3. Also not sure how this application approaches embedding but I'll generally assume there's direct network communication between the "embedding application" and APITable (Instead of just embedding via iframes which would be working around the embedding application anyway). My main intent of opening this is to clarify the use of the AGPL here, since It's often mis-quoted/applied which can further push confusion in the open source community.

From my understanding, if a someone modified an APITable, to remove the logo for example (Upon any other changes), they'd have to make their sources available to those they distribute to, where network use includes distribution.  Therefore if APITable was embedded into another application, and parts of APITable were also distributed (again, including just network use) then the source of the modified APITable instance would need to be accessible to the users of that embedding application. 

Your definition above advises I'd need to release the embedding application under the AGPL also. I'm not sure what part of the AGPL requires this. While the AGPL extends distribution to network use, I don't believe it extends to what's considered a derivative work and therefore I don't believe the embedding application needs to be released under a compatible license in any manner. 

Have I misunderstood how embedding works and how the license applies here?

**Comment by mr-kelly** [comment]
Hi @ssddanbrown 

My apologies for the confusion and thank you for your thoughtful question.

In simple terms, APITable's AGPL license implies:

1. You can be free to use the software for yourself or your organisation, even for commercial purposes.
2. <ins>**You can be free to copy, distribute and/or modify the software with the original copyright notice.**</ins>
3. <ins>**You can't deploy a hosted version for public users without the original copyright notice.**<ins>
4. You can't close-source your modifications to the software.

I assume that (1) and (4) are clear to most people.

Let's discuss the two underlined items (2) and (3).

The AGPL is almost identical to the GPL, except for this addition to Section 13 [^ref1]:

> Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. […]

This has one direct implication — if you let users access any AGPL licensed software over a network, then that is also a form of distribution. This is what the GPL had missed out.

The AGPL License is based on GPL v3. It has the same requirements, plus the statement regarding remote access via a network. [^ref2]

Users of AGPL-licensed code must:

1. <ins>**Include a copy of the full license text and the original copyright notice**</ins>
2. State all significant changes made to the original software
3. Make available the source code when you distribute any works based on the licensed software
4. <ins>**Include any installation information necessary to update and reinstall the software if the program is being used as part of a consumer device**</ins>

These requirements are identical to those of GPL v3, other than the source code sharing requirement when the code is modified and made available remotely via a network. The AGPL adds a requirement:

> If you make access to modified software available to users over a network, you must make your source code available to those users.

In this case, if one removes the "Powered by APITable" and embeds it into another application, it implies he <ins>**removed a copy of the full license text and the original copyright notice**</ins> and <ins>**removed any installation information necessary to update and reinstall the software if the program is being used as part of a consumer device**</ins>.

APITable does not permit rebranding without some restrictions. If you need to rebrand, you have to contact APITable for an enterprise license.

Furthermore, sincerely and respectfully, the APITable embedding license was inspired by [this license](https://www.metabase.com/license/).

You can see similar licenses and policies, and also some of the similar words we use.



Due to the fact that it is easy for others to get confused about our embed license, looking forward to hearing from you more.
This will enable us to improve the software.
Thank you very much!

We are going to demonstrate this more clearly in [LICENSING.md](https://github.com/apitable/apitable/blob/develop/LICENSING.md).

[^ref1]: https://medium.com/swlh/understanding-the-agpl-the-most-misunderstood-license-86fd1fe91275
[^ref2]: https://fossa.com/blog/open-source-software-licenses-101-agpl-license/

**Comment by ssddanbrown** [comment]
Thank you very much for the detailed response. I agree with a lot of what's written, but I feel I disagree with the following, which appears the main part surrounding branding:

> In this case, if one removes the "Powered by APITable" and embeds it into another application, it implies he removed a copy of the full license text and the original copyright notice and removed any installation information necessary to update and reinstall the software if the program is being used as part of a consumer device.

I feel that's a massive leap in logic. From what I can tell, the APLGv3 is not overly clear on how access to the source & notices must be provided. There are many ways people could provide that, I don't see how it relates to your own branding. If I removed the logo, but added a `Find source code here` link instead, surely that would suffice?

Additionally, I'm still not clear how the details provided explain why I'd "need to release your own embedding application under the AGPL.". Maybe I'm misunderstanding "embedding application" here, do you mean that to be my modified version APITable in this case, or does this refer to application where APITable is being embedded within?

> Furthermore, sincerely and respectfully, the APITable embedding license was inspired by [this license](https://www.metabase.com/license/).

Ah! Thanks for that. Metabase setup looks even more confusing. They have [this non-open license](https://github.com/metabase/metabase/blob/master/LICENSE-EMBEDDING.txt) which applies to [one file](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/app-embed.js) and it's not mentioned in their readme or [licensing file](https://github.com/metabase/metabase/blob/master/LICENSE.txt). I may raise this with them since it's quite unclear.

**Comment by kwp-lab** [comment]
In short, You are free to use APItable in your embedding application as long as the copyright "Powered by APITable" is preserved (do not change anything).
When you remove the "Powered by APITable" information (or make any other changes), you will need to contact APITable for an enterprise license.
If you do not want to buy an enterprise license, in this case, you will need to release your own embedding application under the AGPL.

**Comment by ssddanbrown** [comment]
@kwp-lab Sure, I get what you are asking, I just don't see how the AGPL requires this, or why I'd need to "release your own embedding application under the AGPL". 

Or are you defining the branding statement as an additional custom requirement/restriction-of-use upon the AGPL license?

**Comment by mr-kelly** [comment]
> @kwp-lab Sure, I get what you are asking, I just don't see how the AGPL requires this, or why I'd need to "release your own embedding application under the AGPL".
> 
> Or are you defining the branding statement as an additional custom requirement/restriction-of-use upon the AGPL license?



> @kwp-lab Sure, I get what you are asking, I just don't see how the AGPL requires this, or why I'd need to "release your own embedding application under the AGPL".
> 
> Or are you defining the branding statement as an additional custom requirement/restriction-of-use upon the AGPL license?

Yes, that is what we are going to do... Give you review later.

**Comment by ssddanbrown** [comment]
Thanks! Keep in mind though that adding restrictions to use or modification to a license would generally make it not considered open source.

If it helps, I did raise the wording with metabase and they [provided some clarification](https://github.com/metabase/metabase/issues/27859).

**Comment by mr-kelly** [comment]
We are going to add more clarification to the [LICENSE](https://github.com/apitable/apitable/blob/develop/LICENSING.md).

And we have this additional [LICENSE-EMBEDDING](https://github.com/apitable/apitable/blob/develop/licenses/LICENSE-EMBEDDING)
