### ISSUE TITLE
feat: cancel NextJS SSR http requeest as far as possible

### ISSUE THREAD

**Issue by mr-kelly** [apitable/apitable#549]
I have an idea for this project.

## Why? 

ffs, when clicking "next record" and many other operations will produce a HTTP request due to the NextJS SSR feature.

It freezes when users do many UI operations.

It appears that this is just "a programmer stuck by a framework".

This should be removed.

## What?

Remove NextJS SSR "getServerSideProps" when clicking the "next record" button.

## How?

- [] Investigate how to remove SSR HTTP requests in tons of UI operations

- [] Code it and remove SSR HTTP request

Ref: https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

**Comment by ZainChen** [comment]
Hi, I added `console.log` to all the pages that use `getServerSideProps`.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/15615524/226177705-f93b348e-442c-4d42-be6f-9ee5e9c8a743.png">

When clicking the "next record", `getServerSideProps` is not triggered. I operated in the place pointed in the figure below, but I am not sure if it's the right place. If it's another place, please let me know.
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/15615524/226177801-64cf0035-e33a-4974-843e-656b3fe71962.png">

However, when I share the page and switch views, SSR will frequently trigger `Api.readShareInfo`, and each time the same data is obtained. This request can be optimized.
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/15615524/226178488-4cd0f66d-99c8-482c-9ed5-ca570cee1af1.png">
Optimization plan: Similar to this, use the singleton design pattern to record the sharing information and only load it once during initialization, so that other operations will not reload it repeatedly.
(Inside `getServerSideProps`, only fetch data that does not change with requests. The dynamic data should be requested by the client. All other cases that use `getServerSideProps` should follow accordingly.)
```tsx

let shareInfo: IShareInfo | null = null;

export const getServerSideProps = async(context: NextPageContext) => {
  if (shareInfo) {
    return {
      props: {
        shareInfo
      }
    };
  }
  axios.defaults.baseURL = getBaseUrl(context);

  if (!context.req?.url) {
    return { props: {}};
  }

  const shareId = getRegResult(context.req.url, shareIdReg);

  if (!shareId) {
    return { props: {}};
  }

  const cookie = context.req?.headers.cookie;

  const headers: Record<string, string> = {};

  if (cookie) {
    headers.cookie = cookie;
  }

  const res = await Api.readShareInfo(shareId, headers);
  const { success, data } = res.data;

  if (success) {
    shareInfo = data;
    return {
      props: {
        shareInfo
      }
    };
  }
  return {
    props: {}
  };
};
```

**Comment by ZainChen** [comment]
Realized that the above code is incorrect. getServerSideProps runs on the server side and shareInfo will be cached on the server, affecting the content of different shared pages viewed by users.

Need to come up with a better way to handle it.

## I have a good idea:

Regarding the issue with getServerSideProps, perhaps using Shallow Routing can be considered. I tried it out and the actual result is consistent with the explanation in the documentation.
https://nextjs.org/docs/routing/shallow-routing
![image](https://user-images.githubusercontent.com/15615524/226518128-29d88a80-f942-4d29-b3d1-4fbdae1b7e58.png)
![image](https://user-images.githubusercontent.com/15615524/226518202-e46c63f9-3810-4325-af3e-0f82bbd95e07.png)

The reason why we couldn't reproduce the issue mentioned by [mr-kelly](https://github.com/mr-kelly) before was probably because the "next record" button used `Router.push` with `shallow: true` added, which was modified last week.
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/15615524/226518552-4e4260a4-132f-47c8-bcad-109c4337419e.png">

## How?

- [ ] Design more flexible parameters for the getHistoryMethod to avoid affecting other functionalities.
- [ ] Add the `shallow: true` option separately for the operations that require it.

**Comment by JaneSu** [comment]
The issue was caused by middleware and the relevant code has been deleted.
