### ISSUE TITLE
feat: arm64 dual image build

### ISSUE THREAD

**Issue by mr-kelly** [apitable/apitable#66]
I have an idea for this project.

# Why? 

Let APITable image runs on ARM64 architect server.

Currently we are using the AMD64 docker image which some users will encounter some problems on ARM64 computer like macOS under M1 chip.

Related issue https://github.com/apitable/apitable/issues/67

# What?

Use `buildx` command to build dual architect image.

# How?

- [ ] Github Action modify to support buildx multi-platform

**Comment by networkhermit** [comment]
https://github.com/apitable/apitable/issues/67

**Comment by nevertoday** [comment]
求恢复！

**Comment by networkhermit** [comment]
For anyone interested in native arm64/apple silicon container images: just as amd64 emulation on m1 docker cause bad performance, building arm64 images on amd64 github runner is also extremely slow. We are working toward a acceptable solution.

**Comment by nevertoday** [comment]
这个问题，能不能催你们这些大神？每天测一测，结果都卡在：
![image](https://user-images.githubusercontent.com/166048/219044393-e0b30a27-ce6f-4dc3-bd4b-192c69642a6c.png)

**Comment by networkhermit** [comment]
https://github.com/apitable/apitable/issues/307#issuecomment-1431393766

> 这个问题，能不能催你们这些大神？每天测一测，结果都卡在： ![image](https://user-images.githubusercontent.com/166048/219044393-e0b30a27-ce6f-4dc3-bd4b-192c69642a6c.png)

@nevertoday Thank you very much for testing apitable. I closed https://github.com/apitable/apitable/issues/67 and https://github.com/apitable/apitable/issues/307 because there are too many bug reports and feedback related with arm64 / apple sillicon images, and it is better to discuss the progress and obstacles in a common issue like this one.

As for the issue of init-db stuck indefinitely on m1/m2, we also suffer from it and we do understand the annoyance and bad user experience.

> For anyone interested in native arm64/apple silicon container images: just as amd64 emulation on m1 docker cause bad performance, building arm64 images on amd64 github runner is also extremely slow. We are working toward a acceptable solution.

I shared the main issue of adding arm64 image build to github action last week. Please pay attention to the comments.

**Comment by nevertoday** [comment]
我很懊恼， 我太想早点用上这个了，刚需~ 
请问能透露，我大概要等多久？
我看到这个问题去年很早就有人反馈了....

**Comment by nevertoday** [comment]
我相信一定有什么巧妙的办法，解决这个问题的，第六感~

**Comment by networkhermit** [comment]
> 我很懊恼， 我太想早点用上这个了，刚需~ 请问能透露，我大概要等多久？ 我看到这个问题去年很早就有人反馈了....

If everything goes well, we will finish the arm64 image build support in the coming weeks. I would notify you once there is beta version to test.

**Comment by nevertoday** [comment]
thank u so so so much !

**Comment by showonne** [comment]
mark

**Comment by zhangyz11** [comment]
mark

**Comment by nevertoday** [comment]
单纯的对着天空大喊一声：r u ready ? @networkhermit

**Comment by nevertoday** [comment]
大佬们， 有希望了么？ 我看到 在in progress 了

**Comment by networkhermit** [comment]
Nope. The arm64 images still have issues running and not ready for test. But it's in our roadmap and we are working on it. Just stay tuned!

**Comment by ZainChen** [comment]
I am using a Mac with an M1 chip.

Tried building a dual-platform image for `init-db` with `linux/amd64` and `linux/arm64` using M1. The image can be found here: [zainchen/init-db:latest](https://hub.docker.com/r/zainchen/init-db/tags).

## Steps taken:
1. Changed `IMAGE_INIT_DB=apitable/init-db:latest` to `IMAGE_INIT_DB=zainchen/init-db:latest` in the `.env` file.
2. Cleared all containers in `docker` `apitable-devenv`.
3. Executed `make dataenv`.

Sometimes all the steps complete successfully, but sometimes it gets stuck at `pre-init-db`, `init-db`, or `init-appdata`.

## Temporary Solution:
1. Checked `Logs` in `Docker Desktop`. If the logs haven't changed for a long time and there's no completion prompt, restart the current container (if restarting doesn't work, repeat the process in step 2).
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/15615524/225570957-8e6b71f6-d09f-40e8-b5f4-a57bf0f8156a.png">
2. Assuming that the containers for `mysql`, `minio`, `redis` and `rabbitmq` are all running properly, the three initialization containers in the following figure should be executed successfully in order.
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/15615524/225570816-bb35c4d5-edfb-45e4-97ad-78237814eb85.png">

## Analysis:
- Tried changing `DATAENV_SERVICES := mysql minio redis rabbitmq init-db init-appdata` in the `Makefile` to `DATAENV_SERVICES := mysql minio redis rabbitmq init-db`, ensuring that all images are using `linux/arm64` (Due to the lack of source code for the `init-appdata` image, there is no `linux/arm64` image available.). The results are sometimes all steps can be completed successfully at once, but sometimes it gets stuck at `pre-init-db` or `init-db` (requires manual restart to succeed).
- When these three containers `pre-init-db`, `init-db`, and `init-appdata` are all using the `linux/amd64` architecture, the results are sometimes all steps can be completed successfully at once, but sometimes it gets stuck at `pre-init-db` or `init-db` (requires manual restart to succeed).
- Also tried adjusting the `CPU` and `Memory` settings to the maximum in `Docker Desktop`.
- Based on the above phenomenon, it is possible that the `linux/amd64` architecture is not the main cause of container running stuck. It is suspected that the code executed by `init-db` and `init-appdata` may have compatibility issues with the `linux/arm64` architecture. Do you experience occasional initialization failures on Macs with Intel chips?

**Comment by nevertoday** [comment]
真的没有看明白~ sorry 是要自己手动clone 到本地然后修改什么东西么？

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/226084285-6bccc9e6-a355-4938-a440-bb92f1db29ee.png)
我还是卡在这个环节，修改了.env

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/226084596-76e55e2e-0a70-4842-8024-24b6ef819581.png)

**Comment by ziqiangai** [comment]
> ![图像](https://user-images.githubusercontent.com/166048/226084596-76e55e2e-0a70-4842-8024-24b6ef819581.png)
Try restarting manually, clear the old container, and re-execute `make dataenv`.

**Comment by ZainChen** [comment]
> ![image](https://user-images.githubusercontent.com/166048/226084596-76e55e2e-0a70-4842-8024-24b6ef819581.png)

手动关闭卡住的镜像，从 pre-init-db-1 开始重新启动，多试几次试试，有时候我也会卡主，需要多次尝试。

**Comment by ZainChen** [comment]
> > ![图像](https://user-images.githubusercontent.com/166048/226084596-76e55e2e-0a70-4842-8024-24b6ef819581.png)
> > Try restarting manually, clear the old container, and re-execute `make dataenv`.

Manually close the stuck image and restart from pre-init-db-1, try several times, sometimes I also get stuck and need to try multiple times.

**Comment by nevertoday** [comment]
手动启动之后， 总是等一下子就退出了。奇怪了， Thank u so much!
![image](https://user-images.githubusercontent.com/166048/226090416-cabcda18-7510-4eb6-9ed0-403dd228ec57.png)

**Comment by ZainChen** [comment]
> Thank u so much!

启动后退出是正常情况，说明执行完成了，点进去看 Logs，看到提示 successfully，说明成功了
<img width="717" alt="image" src="https://user-images.githubusercontent.com/15615524/226092532-084a3c11-4c17-4edd-82f9-aa013392a26e.png">

还有就是，初始化程序不可同时运行，需要按照我上面标注的顺序来，docker-compose.yaml 文件的 depends_on 中配置了执行依赖关系，估计执行顺序很重要
<img width="806" alt="image" src="https://user-images.githubusercontent.com/15615524/226092612-756ebe06-645a-4491-ade9-3bc9a6116706.png">

**Comment by nevertoday** [comment]
按照之前213顺序操作了之后， 还是不能正常打开；请问这个最终访问页面，地址是多少？ 我看看到9000和3306我这边都不能打开， 只有rabbitmq本地，能打开有界面显示~

![image](https://user-images.githubusercontent.com/166048/226115637-ff137bdc-b2d5-49d1-8f9b-8adc738d6c7d.png)

这个hv会自动退出： init-db-1

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/226115794-ab4da551-7910-4e93-880e-7ff1d7766a44.png)

**Comment by ZainChen** [comment]
> 这个hv会自动退出： init-db-1

最终页面的访问地址是：http://localhost:3000
会自动退出是正常的，init 开头的三个镜像都变为 Exited，且没有异常之后，再按照这里的开发指南操作：
https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md#start-development-environment

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/226154440-a7c6848f-d145-4958-a51c-c0ed67df5f16.png)

init 的三个都变成exited ... 倒是没有我是running 状态~ 然后一直卡在这个waiting

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/226154512-425a91ce-80e4-48d9-a0fc-d47b06fe3b66.png)
我是全部都能稳定running 之后， make dataenv 
 然后就没有然后了，只留下等待了

**Comment by ZainChen** [comment]
> ![image](https://user-images.githubusercontent.com/166048/226154440-a7c6848f-d145-4958-a51c-c0ed67df5f16.png)
> 
> init 的三个都变成exited ... 倒是没有我是running 状态~ 然后一直卡在这个waiting

你用的是 m1 还是 m2，我是用的 m1，不确定是否和 m1、m2 差异有关，方便的话，可以加我微信（czy19951314），我远程你电脑看看

**Comment by showonne** [comment]
Looking forward to it. 0.0

**Comment by showonne** [comment]
any update ?

**Comment by nevertoday** [comment]
大半年了，我放弃等待队列 。 貌似没有跟进吧

**Comment by networkhermit** [comment]
We have added the experimental multi-arch build for linux/amd64 and linux/arm64, currently it takes aroud 2 hours to build the multi-arch image, due to the extreme long build time we might disable them in the future (at least some of them).

Upon first trial of the arm64 image in an arm64 linux box (and a mac m1), we find the room-server can't start correctly as described in #1107. Manually fix that issue make it works on my arm64 linux and mac m1.

As the mentioned issue is mainly about the nextjs building process, I shall mark this feature as completed. Please open new issue if you find any arm64/m1/m2 compatibility problem. And also note that the arm64 image is still experimental and mainly tested by community members.
