### ISSUE TITLE
fix: Magic Link: Link to multiple records off but Can select multiple by other side

### ISSUE THREAD

**Issue by cloud0072** [apitable/apitable#668]
**Describe the bug**

![20230402103649](https://user-images.githubusercontent.com/34976399/229328470-d357a728-2ae9-443f-9baf-6e62f37bc4a1.png)
![20230402104006](https://user-images.githubusercontent.com/34976399/229328473-8fc39e08-0d2b-4d83-b2a1-b392b89a4b6c.png)

in the form
user1 show be hidden because multiple choices are not allowed

and I strongly recommend adding a unique value option 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pengjin123** [comment]
@cloud0072 Is the Magic Link enabled in your group table to select multiple records，
Because magic link is a two-way association, you have turned off selecting multiple records in the user table, which only indicates that you cannot actively select multiple records in the user table for Magic Link."

**Comment by cloud0072** [comment]
@pengjin123 I can understand your explanation, but it's not entirely logical. We need one to one, one to many, many to many options. The administrator of the table should be able to control these operations

**Comment by arucil** [comment]
You can disable `link to multiple records` in `group` table to create one-to-one linking.
