### ISSUE TITLE
question: Q&A...How to use local mysql

### ISSUE THREAD

**Issue by KJTM** [apitable/apitable#752]
## Any questions?I don't want to use the mysql container in docker, so I should use the local mysql instead

**Comment by pengjin123** [comment]
@networkhermit Could you please help me take a look at this question? Thank you

**Comment by ziqiangai** [comment]
Hi @KJTM ，Thanks for trying APITable. You can use the database client to export the mysql data in docker, and then change the connection parameters of the database in the code, but the system architecture uses docker by default.

**Comment by KJTM** [comment]
> Hi @KJTM ，Thanks for trying APITable. You can use the database client to export the mysql data in docker, and then change the connection parameters of the database in the code, but the system architecture uses docker by default.

well,I copied the database to the local mysql, and then changed the mysql parameters of ”.env“. At the same time, some parameters of ”docker-compose.yaml“ have been modified. 
The ”init-db“, ”pre-init-db“, ”mysql“ and other containers in it are interdependent. When I remove the mysql configuration in the ”docker-compose.yaml“ file, other containers will report errors accordingly. So I tried to untangle the dependencies, but failed, still can't use local mysql instead

**Comment by networkhermit** [comment]
@KJTM

Have you rerun `docker compose up -d` after modifying `.env`? If you remove the mysql block from `docker-compose.yaml`, you must adjust the other services accordingly, because it indeed has inter-dependencies.

As an alternative, you can change the default username and password of the bundled mysql, and modify the `.env` to your local mysql (Don't forget to run `docker compose up -d` to make it effective).
