### ISSUE TITLE
fix: BUG...robot bug

### ISSUE THREAD

**Issue by cchh2277** [apitable/apitable#859]
**Describe the bug**
use Column content is faild,insert  is success,but value=null.
use Basic info is success,

![image](https://github.com/apitable/apitable/assets/128670031/19f2d3a0-0b4f-4034-b351-d2a9dac9a85c)

**Comment by nagisakon** [comment]
Please carefully check your input and operations on the robot. The reason for the error is that you did not add "" on the variables. Since this is not a bug, please do not frequently raise issues about bugs. If you have more questions, you can join our discord discussion >>> https://discord.com/invite/TwNb9nfdBU

**Comment by cchh2277** [comment]
123

**Comment by cchh2277** [comment]
![image](https://github.com/apitable/apitable/assets/128670031/93095173-332d-4892-8a3d-2ae9cdc34121)
@nagisakon

**Comment by cchh2277** [comment]
![image](https://github.com/apitable/apitable/assets/128670031/87c5996c-017a-4dce-b3c0-4cbae5063e5b)
![image](https://github.com/apitable/apitable/assets/128670031/5302876f-8c66-4821-9bea-7d17151a3a9c)
