### ISSUE TITLE
feat: Optimize the working day display rules of Gantt Chart

### ISSUE THREAD

**Issue by jhk5263** [apitable/apitable#908]
![ad3b90d9-8ddb-487f-b955-2b61334bf5cc](https://github.com/apitable/apitable/assets/71970354/f5b65866-d831-48f4-8f8d-5878271ffcc3)

打开只统计工作日时 能否把旁白图表内对应的星期几给隐藏起来，这样整体看起来会更直观

如 工作日设置为 一 四 六
旁边的图表就只显示一四六梭对应的日期

**Comment by pengjin123** [comment]
@jhk5263 
The setting for workdays is only counted towards the total number of workdays when calculating the workday count. If it is not set as a workday, it will not be included in the actual number of workdays.

**Comment by Alex-hufeng** [comment]
Thank you for your suggestion. Can you add the details according to the template submitted by issue? So that other readers can more easily understand your intentions.

https://github.com/apitable/apitable/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=feat%3A+A+brief+description+of+your+requested+feature
