### ISSUE TITLE
May I ask how to achieve paging to obtain data

### ISSUE THREAD

**Issue by coyclei** [apitable/apitable#957]
May I ask how to achieve paging to obtain data, because the amount of data in the system may be large, which will make users wait too long when opening the data table

**Comment by arucil** [comment]
This is hard, because the filtering, grouping, and sorting of records rely on cell values being fetched and computed (e.g. formulas), so we have to fetch all records before performing these operations. If we want record pagination as well as filtering & grouping & sorting, it requires a redesign of the underlying architecture and is too much work, so we won't consider it in the near future.
